screener_url: 'https://www.nasdaq.com/market-activity/stocks/screener'
stocks_url: 'https://www.nasdaq.com/market-activity/stocks/'
total_pages_xpath: '/html/body/div[2]/div/main/div[2]/article/div[3]/div[1]/div/div/div[3]/div[5]/div/button[8]'
next_page_button_xpath: '/html/body/div[2]/div/main/div[2]/article/div[3]/div[1]/div/div/div[3]/div[5]/button[2]'
key_data_header_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[1]/h2'
see_also_banner_xpath: '/html/body/div[2]/div/main/div[2]/article/div[3]/div[1]/aside/div'
symbols_in_page_xpath: '/html/body/div[2]/div/main/div[2]/article/div[3]/div[1]/div/div/div[3]/div[3]/table/tbody/tr['
name_xpath: '/html/body/div[2]/div/main/div[2]/div[3]/section/div[2]/div/div/div[1]/div[1]/div[1]/h1/span'
price_xpath: '/html/body/div[2]/div/main/div[2]/div[3]/section/div[2]/div/div/div[1]/div[1]/div[2]/div[2]/div[2]/span[1]/span[2]'
pricing_changes_xpath: '/html/body/div[2]/div/main/div[2]/div[3]/section/div[2]/div/div/div[1]/div[1]/div[2]/div[2]/div[2]/div/span[1]'
pricing_change_percentage_xpath: '/html/body/div[2]/div/main/div[2]/div[3]/section/div[2]/div/div/div[1]/div[1]/div[2]/div[2]/div[2]/div/span[2]'
sector_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[1]/tr[2]/td[2]'
industry_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[1]/tr[3]/td[2]'
market_cap_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[2]/tr[1]/td[2]'
share_volume_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[1]/tr[6]/td[2]'
earnings_per_share_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[2]/tr[4]/td[2]'
annualized_dividend_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[2]/tr[5]/td[2]'
dividend_pay_date_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[2]/tr[7]/td[2]'
yield_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[2]/tr[8]/td[2]'
beta_xpath: '/html/body/div[2]/div/main/div[2]/div[6]/div/div[1]/div/div[2]/table/tbody[2]/tr[9]/td[2]'